# Generated by Django 5.1.1 on 2024-10-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_document_type',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'ID Card'), ('DRIVERS_LICENSE', 'Driver’s License')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
    ]
