# Generated by Django 5.1.1 on 2024-10-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate_to_usd',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
